export default [
    {
        id: 1,
        name: 'Naruto',
        img: './assets/images/1.jpg',
        category: ['anime'],
        width: 30,
        height: 40,
        color: ['white', 'orange', 'yellow', 'red'],
        price: 10.99,
        year: 2019,
        country: 'japan',
        rating: 5,
        count: 1,
    },
    {
        id: 2,
        name: "JoJo's Bizarre Adventure: Golden Wind",
        img: './assets/images/2.jpg',
        category: ['anime'],
        width: 45,
        height: 75,
        color: ['black', 'red', 'blue'],
        price: 12.99,
        year: 2022,
        country: 'japan',
        rating: 4,
        count: 12,
    },
    {
        id: 3,
        name: 'Tokyo Ghoul Kaneki Ken',
        img: './assets/images/3.jpg',
        category: ['anime'],
        width: 45,
        height: 35,
        color: ['white', 'black'],
        price: 11.49,
        year: 2022,
        country: 'japan',
        rating: 3,
        count: 35,
    },
    {
        id: 4,
        name: 'Noragami',
        img: './assets/images/4.jpg',
        category: ['anime'],
        width: 45,
        height: 35,
        color: ['grey', 'black'],
        price: 13.99,
        year: 2022,
        country: 'japan',
        rating: 4,
        count: 10,
    },
    {
        id: 5,
        name: 'Amnesia',
        img: './assets/images/5.jpg',
        category: ['anime'],
        width: 40,
        height: 30,
        color: ['white', 'black', 'green', 'yellow', 'orange'],
        price: 15.69,
        year: 2022,
        country: 'eu',
        rating: 5,
        count: 16,
    },
    {
        id: 6,
        name: 'Terminator',
        img: './assets/images/6.jpg',
        category: ['vintage', 'movie'],
        width: 55,
        height: 65,
        color: ['black', 'red'],
        price: 19.99,
        year: 2020,
        country: 'usa',
        rating: 4,
        count: 28,
    },
    {
        id: 7,
        name: 'Depeche Mode',
        img: './assets/images/7.jpg',
        category: ['vintage'],
        width: 45,
        height: 75,
        color: ['black', 'red'],
        price: 15.49,
        year: 2016,
        country: 'eu',
        rating: 5,
        count: 14,
    },
    {
        id: 8,
        name: 'Brewco',
        img: './assets/images/8.jpg',
        category: ['vintage'],
        width: 35,
        height: 45,
        color: ['orange', 'red', 'blue'],
        price: 8.49,
        year: 2010,
        country: 'usa',
        rating: 4,
        count: 7,
    },
    {
        id: 9,
        name: 'Back to the Future Part III',
        img: './assets/images/9.jpg',
        category: ['vintage', 'movie'],
        width: 55,
        height: 65,
        color: ['black', 'orange', 'brown'],
        price: 19.99,
        year: 2018,
        country: 'usa',
        rating: 4,
        count: 40,
    },
    {
        id: 10,
        name: 'Marilyn Monroe',
        img: './assets/images/10.jpg',
        category: ['vintage', 'movie'],
        width: 55,
        height: 65,
        color: ['black', 'orange', 'red'],
        price: 17.99,
        year: 2016,
        country: 'usa',
        rating: 5,
        count: 3,
    },
    {
        id: 11,
        name: 'Porsche',
        img: './assets/images/11.jpg',
        category: ['vintage', 'car'],
        width: 25,
        height: 40,
        color: ['green', 'red', 'white'],
        price: 9.99,
        year: 2006,
        country: 'eu',
        rating: 4,
        count: 18,
    },
    {
        id: 12,
        name: 'Brazil',
        img: './assets/images/12.jpg',
        category: ['vintage', 'nature'],
        width: 30,
        height: 50,
        color: ['green', 'blue', 'orange'],
        price: 10.99,
        year: 2016,
        country: 'usa',
        rating: 3,
        count: 10,
    },
    {
        id: 13,
        name: 'Undertale',
        img: './assets/images/13.jpg',
        category: ['games'],
        width: 45,
        height: 35,
        color: ['black', 'white'],
        price: 13.79,
        year: 2021,
        country: 'eu',
        rating: 4,
        count: 8,
    },
    {
        id: 14,
        name: 'Genshin Impact',
        img: './assets/images/14.jpg',
        category: ['games'],
        width: 45,
        height: 65,
        color: ['red', 'white'],
        price: 15.99,
        year: 2022,
        country: 'usa',
        rating: 5,
        count: 11,
    },
    {
        id: 15,
        name: 'Doom',
        img: './assets/images/15.jpg',
        category: ['games'],
        width: 45,
        height: 65,
        color: ['black', 'red'],
        price: 16.39,
        year: 2021,
        country: 'usa',
        rating: 4,
        count: 12,
    },
    {
        id: 16,
        name: 'Brawl Stars',
        img: './assets/images/16.jpg',
        category: ['games'],
        width: 70,
        height: 50,
        color: ['blue', 'red'],
        price: 17.99,
        year: 2021,
        country: 'usa',
        rating: 3,
        count: 23,
    },
    {
        id: 17,
        name: 'Minecraft',
        img: './assets/images/17.jpg',
        category: ['games'],
        width: 45,
        height: 65,
        color: ['black', 'brown', 'green', 'blue'],
        price: 15.99,
        year: 2020,
        country: 'eu',
        rating: 4,
        count: 10,
    },
    {
        id: 18,
        name: 'Tram',
        img: './assets/images/18.jpg',
        category: ['places'],
        width: 45,
        height: 70,
        color: ['black', 'grey', 'yellow'],
        price: 13.99,
        year: 2012,
        country: 'eu',
        rating: 4,
        count: 2,
    },
    {
        id: 19,
        name: 'Amsterdam',
        img: './assets/images/19.jpg',
        category: ['places'],
        width: 45,
        height: 60,
        color: ['white', 'grey', 'brown'],
        price: 13.49,
        year: 2013,
        country: 'eu',
        rating: 4,
        count: 3,
    },
    {
        id: 20,
        name: 'London',
        img: './assets/images/20.jpg',
        category: ['places', 'vintage'],
        width: 30,
        height: 45,
        color: ['black', 'red', 'orange'],
        price: 10.99,
        year: 2017,
        country: 'eu',
        rating: 4,
        count: 24,
    },
    {
        id: 21,
        name: 'Architecture',
        img: './assets/images/21.jpg',
        category: ['places'],
        width: 50,
        height: 40,
        color: ['black', 'grey', 'white'],
        price: 12.29,
        year: 2019,
        country: 'eu',
        rating: 4,
        count: 5,
    },
    {
        id: 22,
        name: 'Provence',
        img: './assets/images/22.jpg',
        category: ['places'],
        width: 50,
        height: 40,
        color: ['pink', 'orange', 'brown'],
        price: 12.29,
        year: 2020,
        country: 'eu',
        rating: 5,
        count: 6,
    },
    {
        id: 23,
        name: 'Paris',
        img: './assets/images/23.jpg',
        category: ['places'],
        width: 50,
        height: 40,
        color: ['brown', 'red', 'yellow'],
        price: 14.29,
        year: 2021,
        country: 'eu',
        rating: 5,
        count: 27,
    },
    {
        id: 24,
        name: 'Night City',
        img: './assets/images/24.jpg',
        category: ['places'],
        width: 55,
        height: 45,
        color: ['black', 'red', 'orange', 'brown'],
        price: 15.79,
        year: 2022,
        country: 'usa',
        rating: 4,
        count: 8,
    },
    {
        id: 25,
        name: 'Japanese',
        img: './assets/images/25.jpg',
        category: ['places', 'nature'],
        width: 35,
        height: 20,
        color: ['black', 'red', 'white', 'grey'],
        price: 8.99,
        year: 2018,
        country: 'japan',
        rating: 4,
        count: 19,
    },
    {
        id: 26,
        name: 'Monstera',
        img: './assets/images/26.jpg',
        category: ['nature'],
        width: 80,
        height: 100,
        color: ['green'],
        price: 28.99,
        year: 2020,
        country: 'japan',
        rating: 3,
        count: 10,
    },
    {
        id: 27,
        name: 'Tree',
        img: './assets/images/27.jpg',
        category: ['nature'],
        width: 50,
        height: 40,
        color: ['grey'],
        price: 13.49,
        year: 2021,
        country: 'eu',
        rating: 4,
        count: 21,
    },
    {
        id: 28,
        name: 'Black Butterfly',
        img: './assets/images/28.jpg',
        category: ['nature'],
        width: 60,
        height: 45,
        color: ['black', 'green'],
        price: 13.99,
        year: 2022,
        country: 'usa',
        rating: 5,
        count: 12,
    },
    {
        id: 29,
        name: 'Sunset',
        img: './assets/images/29.jpg',
        category: ['nature'],
        width: 55,
        height: 45,
        color: ['beige', 'blue', 'green'],
        price: 11.49,
        year: 2018,
        country: 'usa',
        rating: 5,
        count: 3,
    },
    {
        id: 30,
        name: 'Tree',
        img: './assets/images/30.jpg',
        category: ['nature', 'art'],
        width: 35,
        height: 45,
        color: ['blue', 'green'],
        price: 10.99,
        year: 2019,
        country: 'eu',
        rating: 3,
        count: 8,
    },
    {
        id: 31,
        name: 'Water fruit',
        img: './assets/images/31.jpg',
        category: ['nature'],
        width: 45,
        height: 30,
        color: ['blue', 'green'],
        price: 14.49,
        year: 2020,
        country: 'usa',
        rating: 4,
        count: 5,
    },
    {
        id: 32,
        name: 'Pirates',
        img: './assets/images/32.jpg',
        category: ['nature', 'movie'],
        width: 45,
        height: 30,
        color: ['black', 'grey', 'orange'],
        price: 14.99,
        year: 2015,
        country: 'usa',
        rating: 4,
        count: 9,
    },
    {
        id: 33,
        name: 'Pierre-Joseph Redoute',
        img: './assets/images/33.jpg',
        category: ['art', 'nature'],
        width: 45,
        height: 60,
        color: ['white', 'green', 'pink'],
        price: 14.99,
        year: 2016,
        country: 'eu',
        rating: 5,
        count: 2,
    },
];
